name: Auto Sync with Upstream

on:
  schedule:
    - cron: '0 0 * * *' # 每天执行一次，这是一个示例定时任务，可以根据需要修改
  workflow_dispatch: # 也可以手动触发同步

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add upstream
      run: |
        git remote add upstream https://github.com/hjdhnx/drpy-node.git

    - name: Pull changes from upstream
      run: |
        git fetch upstream
        git pull upstream main --rebase

    - name: Push changes to your fork
      run: |
        git push origin main
