name: Auto Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0:00 运行
  workflow_dispatch:      # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # 拉取所有历史提交

      - name: Pull changes from upstream
        run: |
          git remote add upstream https://github.com/hjdhnx/drpy-node.git
          git fetch upstream
          git merge upstream/main -X theirs --no-edit  # 自动解决冲突，倾向于上游分支

      - name: Commit and push changes
        run: |
          git push origin main
