name: Auto Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # 每天执行一次，这是一个示例定时任务，可以根据需要修改
  workflow_dispatch: # 也可以手动触发同步

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Fork
        uses: actions/checkout@v3
        with:
          # 递归获取所有子模块，根据需要添加
          submodules: true
          # 设置为从上游仓库拉取最新代码
          fetch-depth: 0
      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/hjdhnx/drpy-node
      - name: Fetch Upstream Changes
        run: git fetch upstream
      - name: Merge Upstream into Fork's Main Branch
        run: git merge upstream/main -m "Auto sync with upstream"
      - name: Push Changes to Fork
        run: git push origin main
